fileVersion: 1
id: "837"
mappingDefinitions:
  SOURCE_DATA:
    database: VINITHA_DEV
    schema: SRC_DEV
  TARGET_ACC:
    database: VINITHA_DEV
    schema: DEP_DEV
  TARGET_DB:
    database: TANVI_DEV
    schema: QA
  TARGET_DEV:
    database: TANVI_DEV
    schema: SOURCE
name: New Environment
type: Environment
