fileVersion: 1
id: "593"
mappingDefinitions:
  SOURCE_DATA:
    database: SMHASKE_DEV
    schema: SOURCE_TABLES
  TARGET_ACC:
    database: ANANDHIS_DEV
    schema: TARGET_ACC
  TARGET_DB:
    database: SMHASKE_DEV
    schema: TARGET_TEST
  TARGET_DEV:
    database: ANANDHIS_DEV
    schema: TARGET_DEV
name: New Environment - QA
type: Environment
