@id("992c4341-c109-4d7d-8b70-75245c3f4a75")
@nodeType("696")
SELECT
    N_NATIONKEY,
    N_NAME AS NATION_NAME,
    R_REGIONKEY,
    R_NAME AS REGION_NAME
FROM {{ ref('SOURCE_DATA', 'NATION_TEST') }} NATION_TEST
INNER JOIN {{ ref('SOURCE_DATA', 'REGION_PK') }} REGION_PK
    ON NATION_TEST.N_REGIONKEY = REGION_PK.R_REGIONKEY
ORDER BY
    R_NAME,
    N_NAME