@id("d15b507f-6abb-40b9-bcfa-8eedaf353b6e")
@nodeType("696")
SELECT
     NATION_TEST."N_NAME" AS "N_NAME",
     NATION_HISTORY."N_NAME" AS "N_NAME"
FROM {{ ref('SOURCE_DATA', 'NATION_TEST') }} "NATION_TEST"
INNER JOIN {{ ref('SOURCE_DATA', 'NATION_HISTORY') }} "NATION_HISTORY"
ON "NATION_TEST".N_NATIONKEY = "NATION_HISTORY".N_NATIONKEY